apiVersion: apps/v1
kind: Deployment
metadata:
  name: raally-backend
  namespace: raally
  labels:
    app: raally-backend
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: raally-backend
  template:
    metadata:
      labels:
        app: raally-backend
        tier: backend
    spec:
      containers:
      - name: raally-backend
        image: raally/backend:latest
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: raally-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: raally-config
              key: PORT
        - name: DEFAULT_LANGUAGE
          valueFrom:
            configMapKeyRef:
              name: raally-config
              key: DEFAULT_LANGUAGE
        - name: REDIS_URL
          value: "redis://$(REDIS_HOST):$(REDIS_PORT)"
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: raally-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: raally-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: raally-secrets
              key: REDIS_PASSWORD
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: raally-config
              key: KAFKA_BROKERS
        - name: KAFKA_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: raally-config
              key: KAFKA_CLIENT_ID
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: raally-secrets
              key: JWT_SECRET
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: raally-secrets
              key: DATABASE_URL
        - name: EMAIL_SMTP_USER
          valueFrom:
            secretKeyRef:
              name: raally-secrets
              key: EMAIL_SMTP_USER
        - name: EMAIL_SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: raally-secrets
              key: EMAIL_SMTP_PASS
        livenessProbe:
          httpGet:
            path: /api/health/live
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health/ready
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: raally-backend-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: raally-backend-service
  namespace: raally
  labels:
    app: raally-backend
spec:
  selector:
    app: raally-backend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    name: http
  type: ClusterIP
